DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;

CREATE TABLE users
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login       VARCHAR(25)     NOT NULL,
    password    VARCHAR(30)     NOT NULL
);

CREATE TABLE tasks
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     int             NOT NULL,
    name        VARCHAR(50)     NOT NULL,
    status      VARCHAR(25)     NOT NULL
)

